### ISSUE TITLE
Widget abDatepicker is not installed

### ISSUE THREAD

**Issue by momos95** [eureka2/G6K#28]
Hello,

thank you for the good job you did with the simulator.

So, I have an issue, I am trying to import a similator .xml and I got this error : **'Simulator Importer: The widget 'abDatepicker' doesn't exists'**

Could you help me please ?

Warmest Regards,
Mamadou

**Comment by eureka2** [comment]
Hello

Can you verify that :
1) the file "config\packages\g6k.yml" contains the  lines : 
```
    widgets:
        abListbox:
            label: Accessible and customizable listbox
            target: [ choice, department, region, country, year, month, day ]
            input: [ select ]
            css:
                - css/listbox.css
            js: 
                - js/listbox.js
                - js/abListbox.js
        abDatepicker:
            label: Accessible and customizable datepicker
            target: [ date ]
            input: [ text ]
            css: 
                - css/datepicker.css
            js: 
                - js/locales/%app_locale%.js
                - js/datepicker.js
                - js/abDatepicker.js
```
2) The file "calcul/assets/base/widgets/abDatepicker/js/abDatepicker.js" exists

Is it possible to upload your xml file here  ?

Best regards
